config/routes.rb
NMSUpdaterBeta::Application.routes.draw do
  devise_for :users, :path_names => { :sign_up => "create_user" }
  resource :nms_updates, only: [:create, :destroy]

  root :to => 'dashboard#index'

  match 'index'   => 'dashboard#index'

  match 'nms_add'     => 'nms_updates#add'
  match 'nms_update'  => 'nms_updates#update'
  match 'nms_remove'  => 'nms_updates#remove'

  match 'process' => 'process#process_page'

  match 'profile' => 'profile#profile_page'











end

app/models/nms_update.rb
class NmsUpdate < ActiveRecord::Base
   attr_accessible :service_type, :basestation, :direction, :device_make, :device_model,
                   :ba_service_number, :partner, :business_name, :address, :ip_address, :comments

   belongs_to :user


   validates :user_id, presence: true

   default_scope order: 'nms_updates.created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :recoverable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username

  has_many :nms_updates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

end

app/controllers/nms_controller.rb
class NmsController < ApplicationController
  before_filter :authenticate_user!

  def add
  end

  def update
  end

  def remove
  end

  def create
  end

end

app/controllers/nms_updates_controller.rb
class NmsUpdatesController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :destroy]

  def add
    @nms_update = current_user.nms_updates.build
  end

  def update
  end

  def remove
  end

  def create
    @nms_update = current_user.nms_updates.build(params[:nms_update])
    if @nms_update.save
      flash[:success] = "NMS Update created!"
      redirect_to nms_add_path
    else
      flash[:alert] = "NMS Update created!"
      render 'nms/add'
    end
  end

  def destroy
  end
end

app/controllers/process_controller.rb
class ProcessController < ApplicationController
  before_filter :authenticate_user!

  def process_page
  end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_filter :authenticate_user!

  def profile_page
    @user = current_user
    @nms_updates = @user.nms_updates.paginate(page: params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_page? (path)
    if current_page?(path)
      raw ('class=active')
    else
      ''
    end
  end

  def active_menu? (path)
    path ? 'active open' : ''
  end

  def skin_method
    case cookies[:SkinCookie]
      when "skin-1"
        "class=skin-1"
      when "skin-2"
        "class=skin-2"
      when "skin-3"
        "class=skin-3"
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/nms_helper.rb
module NmsHelper
end

app/helpers/nms_updates_helper.rb
module NmsUpdatesHelper
end

app/helpers/process_helper.rb
module ProcessHelper

end

app/views/dashboard/index.html.erb
<% provide(:title, 'Dashboard') %>
<% provide(:page_header_description, 'Overview of NMS updates') %>

<%= content_for :page_specific_stylesheets do %>
<% end %>

<%= content_for :inline_stylesheets do %>
  <%# ----------------------None---------------------- %>
<% end %>

<%# Flash Notices - Start %>
<% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">
      <i class="icon-remove"></i>
    </button>

    <strong>
      <i class="icon-ok"></i>
      Success!
    </strong>

    <%= flash[:notice] %>
    <br>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">
      <i class="icon-remove"></i>
    </button>

    <strong>
      <i class="icon-remove"></i>
      Oh snap!
    </strong>

    <%= flash[:alert] %>
    <br>
  </div>
<% end %>
<%# Flash Notices - End %>

<%# Page Content - Start %>
<%# Page Content - End %>

<%= content_for :page_specific_javascripts do %>
<% end %>

<% content_for :inline_javascripts do %>
<% end %>

app/views/layouts/AceAdminLayout/_breadcrumbs_and_search.html.erb
<div id="breadcrumbs">
  <ul class="breadcrumb">
    <li>
      <i class="icon-home"></i>
      <%= link_to "Home", index_path %>
							<span class="divider">
								<i class="icon-angle-right"></i>
							</span>
    </li>
    <li class="active"><%= yield(:title) %></li>
  </ul><!--.breadcrumb-->

  <div id="nav-search">
    <form class="form-search">
							<span class="input-icon">
								<input type="text" placeholder="Search ..." class="input-small search-query" id="nav-search-input" autocomplete="off" />
								<i class="icon-search" id="nav-search-icon"></i>
							</span>
    </form>
  </div><!--#nav-search-->
</div>

app/views/layouts/AceAdminLayout/_javascript_include.html.erb
<!--basic scripts-->

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript">
  window.jQuery || document.write("<script src='assets/jquery-1.9.1.min.js'>"+"<"+"/script>");
</script>
<%= javascript_include_tag "bootstrap.min" %>

<!--page specific plugin scripts-->

<!--[if lte IE 8]>
<script src="/js/"></script>
<![endif]-->

<%= yield :page_specific_javascripts %>

<!--ace scripts-->

<%= javascript_include_tag "ace-elements.min" %>
<%= javascript_include_tag "ace.min" %>
<%= javascript_include_tag "jquery.cookie" %>



<!--inline scripts related to this page-->

<%= yield :inline_javascripts %>


app/views/layouts/AceAdminLayout/_navbar.html.erb
<div class="navbar navbar-inverse">
<div class="navbar-inner">
<div class="container-fluid">

<%= link_to (raw('<small><i class="icon-cloud"></i> NMS Updater <span class="red">Beta</span></small>')), index_path, :class => "brand" %>
<!--/.brand-->

<ul class="nav ace-nav pull-right">

<li class="light-blue user-profile">
  <a data-toggle="dropdown" href="#" class="user-menu dropdown-toggle">
    <img class="nav-user-photo" src="/assets/avatar2.png" alt="Default Photo" />
								<span id="user_info">
									<small>Welcome,</small>
                  <%= user_signed_in? ? current_user.username : "Not signed in" %>
								</span>

    <i class="icon-caret-down"></i>
  </a>

  <ul class="pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-closer" id="user_menu">
    <li>
      <%= link_to (raw('<i class="icon-cog"></i>Settings')), edit_user_registration_path %>
    </li>

    <li>
      <%= link_to (raw('<i class="icon-user"></i>Profile')), profile_path %>
    </li>

    <li class="divider"></li>

    <li>
      <%= link_to (raw('<i class="icon-off"></i>Logout')), destroy_user_session_path %>
    </li>
  </ul>
</li>
</ul><!--/.ace-nav-->
</div><!--/.container-fluid-->
</div><!--/.navbar-inner-->
</div>

app/views/layouts/AceAdminLayout/_page_header.html.erb
<div class="page-header position-relative">
  <h1>
    <%= yield(:title) %>
    <small>
      <i class="icon-double-angle-right"></i>
      <%= yield(:page_header_description) %>
    </small>
  </h1>
</div><!--/.page-header-->

app/views/layouts/AceAdminLayout/_settings_container.html.erb
<div id="ace-settings-container">
  <div class="btn btn-app btn-mini btn-warning" id="ace-settings-btn">
    <i class="icon-cog"></i>
  </div>

  <div id="ace-settings-box">
    <div>
      <div class="pull-left">
        <select id="skin-colorpicker" class="hidden">
          <option data-class="default" value="#438EB9" <%= cookies[:SkinCookie] == 'default' ? 'selected="selected"' : ''%>>#438EB9</option>
          <option data-class="skin-1" value="#222A2D" <%= cookies[:SkinCookie] == 'skin-1' ? 'selected="selected"' : ''%>>#222A2D</option>
          <option data-class="skin-2" value="#C6487E" <%= cookies[:SkinCookie] == 'skin-2' ? 'selected="selected"' : ''%>>#C6487E</option>
          <option data-class="skin-3" value="#D0D0D0" <%= cookies[:SkinCookie] == 'skin-3' ? 'selected="selected"' : ''%>>#D0D0D0</option>
        </select>
      </div>
      <span>&nbsp; Choose Skin</span>
    </div>

    <div>
      <input type="checkbox" class="ace-checkbox-2" id="ace-settings-header" />
      <label class="lbl" for="ace-settings-header"> Fixed Header</label>
    </div>

    <div>
      <input type="checkbox" class="ace-checkbox-2" id="ace-settings-sidebar" />
      <label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
    </div>
  </div>
</div><!--/#ace-settings-container-->

app/views/layouts/AceAdminLayout/_sidebar.html.erb

<% if cookies[:SideBarCookie] == "menu-min" %>
  <div id="sidebar" class="menu-min">
 <% else %>
  <div id="sidebar" >
<% end %>
  <div id="sidebar-shortcuts">
      <div id="sidebar-shortcuts-large">
      <button class="btn btn-small btn-success hidden">
        <i class="icon-signal"></i>
      </button>

      <button class="btn btn-small btn-info hidden">
        <i class="icon-pencil"></i>
      </button>

      <button class="btn btn-small btn-warning hidden">
        <i class="icon-group"></i>
      </button>

      <button class="btn btn-small btn-danger hidden">
        <i class="icon-cogs"></i>
      </button>
    </div>

    <div id="sidebar-shortcuts-mini">
      <span class="btn btn-success hidden"></span>

      <span class="btn btn-info hidden"></span>

      <span class="btn btn-warning hidden"></span>

      <span class="btn btn-danger hidden"></span>
    </div>
  </div><!--#sidebar-shortcuts-->

  <ul class="nav nav-list">
    <li <%= active_page?(index_path) %>>
      <%= link_to (raw('<i class="icon-dashboard"></i><span>Dashboard</span>')), index_path %>
    </li>

    <%= content_tag :li, :class => "#{active_menu?(current_page?(nms_add_path) || current_page?(nms_update_path) || current_page?(nms_remove_path))}" do %>
      <a href="#" class="dropdown-toggle">
        <i class="icon-edit"></i>
        <span>NMS</span>

        <b class="arrow icon-angle-down"></b>
      </a>

      <ul class="submenu">
        <li <%= active_page?(nms_add_path) %>>
          <%= link_to (raw('<i class="icon-double-angle-right"></i>Add')), nms_add_path %>
        </li>

        <li <%= active_page?(nms_update_path) %>>
          <%= link_to (raw('<i class="icon-double-angle-right"></i>Update')), nms_update_path %>
        </li>

        <li <%= active_page?(nms_remove_path) %>>
          <%= link_to (raw('<i class="icon-double-angle-right"></i>Remove')), nms_remove_path %>
        </li>
      </ul>
    <% end %>

    <li <%= active_page?(process_path) %>>
      <%= link_to (raw('<i class="icon-cogs"></i><span>Process</span>')), process_path %>
    </li>
  </ul><!--/.nav-list-->

  <div id="sidebar-collapse">
    <i class="icon-double-angle-left"></i>
  </div>
</div>

app/views/layouts/AceAdminLayout/_stylesheets_include.html.erb
<!--basic styles-->

<%= stylesheet_link_tag "bootstrap.min" %>
<%= stylesheet_link_tag "bootstrap-responsive.min" %>
<%= stylesheet_link_tag "font-awesome.min" %>

<!--[if IE 7]>
<%= stylesheet_link_tag "font-awesome-ie7.min" %>
<![endif]-->

<!--page specific plugin styles-->

<%= yield :page_specific_stylesheets %>

<!--fonts-->

<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" />

<!--ace styles-->
<%= stylesheet_link_tag "ace.min" %>
<%= stylesheet_link_tag "ace-responsive.min" %>
<%= stylesheet_link_tag "ace-skins.min" %>

<!--[if lte IE 8]>
<%= stylesheet_link_tag "ace-ie.min" %>
<![endif]-->

<!--inline styles if any-->

<%= yield :inline_stylesheets %>

app/views/layouts/_footer.html.erb
              <!--PAGE CONTENT ENDS HERE-->
            </div><!--/row-->
          </div><!--/#page-content-->
        <%= render 'layouts/AceAdminLayout/settings_container' %>
      </div><!--/#main-content-->
    </div><!--/.fluid-container#main-container-->
    <a href="#" id="btn-scroll-up" class="btn btn-small btn-inverse">
      <i class="icon-double-angle-up icon-only bigger-110"></i>
    </a>
    <%= render 'layouts/AceAdminLayout/javascript_include' %>
  </body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title><%= yield(:title) %> - NMS Updater Beta</title>

  <meta name="description" content="overview &amp; stats" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <%= render 'layouts/AceAdminLayout/stylesheets_include' %>
</head>

<body <%= skin_method %>>
  <%= render 'layouts/AceAdminLayout/navbar' %>
  <div class="container-fluid" id="main-container">
    <a id="menu-toggler" href="#">
      <span></span>
    </a>
    <%= render 'layouts/AceAdminLayout/sidebar' %>
    <div id="main-content" class="clearfix">
      <%= render 'layouts/AceAdminLayout/breadcrumbs_and_search' %>
      <div id="page-content" class="clearfix">
        <%= render 'layouts/AceAdminLayout/page_header' %>
        <div class="row-fluid">
          <!--PAGE CONTENT BEGINS HERE-->

app/views/layouts/application.html.erb

<% unless user_signed_in? %>
  <%= yield %>
<% else %>
  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
<% end %>


app/views/layouts/blanktemplate.html.erb
<% provide(:title, '') %>
<% provide(:page_header_description, '') %>

<%= content_for :page_specific_stylesheets do %>
<% end %>

<%= content_for :inline_stylesheets do %>
  <%# ----------------------None---------------------- %>
<% end %>


<%# Page Contend - Start %>
<%# Page Contend - End %>

<%= content_for :page_specific_javascripts do %>
<% end %>

<% content_for :inline_javascripts do %>
<% end %>

app/views/nms/add.html.erb
<% provide(:title, 'Add') %>
<% provide(:page_header_description, 'Add new device to NMS') %>

<%= content_for :page_specific_stylesheets do %>
<% end %>

<%= content_for :inline_stylesheets do %>
  <%# ----------------------None---------------------- %>
<% end %>


<%# Page Contend - Start %>
<%# Page Contend - End %>

<%= content_for :page_specific_javascripts do %>
<% end %>

<% content_for :inline_javascripts do %>
<% end %>

app/views/nms_updates/_nms_update.html.erb
<tbody>
<tr>
  <td class="center" style="text-align: center;vertical-align: middle;">
    <label>
      <input type="checkbox">
      <span class="lbl"></span>
    </label>
  </td>
  <td class=""><%= nms_update.service_type %></td>
  <td class=""><%= nms_update.basestation %></td>
  <td class=""><%= nms_update.direction %></td>
  <td class=""><%= nms_update.device_make %></td>
  <td class=""><%= nms_update.device_model %></td>
  <td class=""><%= nms_update.ba_service_number %></td>
  <td class=""><%= nms_update.partner %></td>
  <td class=""><%= nms_update.business_name %></td>
  <td class=""><%= nms_update.address %></td>
  <td class=""><%= nms_update.ip_address %></td>
  <td style="word-wrap: break-word;"><%= nms_update.comments %></td>
  <td class="">Created <%= time_ago_in_words(nms_update.created_at) %> ago.</td>
</tr>
</tbody>

app/views/nms_updates/add.html.erb
<% provide(:title, 'Add') %>
<% provide(:page_header_description, 'Add new device to NMS') %>

<%= content_for :page_specific_stylesheets do %>
<% end %>

<%= content_for :inline_stylesheets do %>
  <%# ----------------------None---------------------- %>
<% end %>


<%# Page Contend - Start %>

<% flash.each do |key, value| %>
  <div class="alert alert-block alert-<%= key %>">
    <button type="button" class="close" data-dismiss="alert">
      <i class="icon-remove"></i>
    </button>
    <i class="icon-ok green"></i>
    <%= value %>
  </div>
<% end %>

<div class="row-fluid">

  <ul class="nav nav-pills">

    <li class="active">
      <a href="#">Big Air</a>
    </li>

    <li class="disabled">
      <a href="#">Allegro</a>
    </li>
  </ul>

  <ul class="nav nav-pills">
    <li class="active">
      <a href="#">Infrastructure</a>
    </li>

    <li>
      <a href="#">Customer</a>
    </li>
  </ul>

  <ul class="nav nav-pills">
    <li class="active">
      <a href="#">Sector Radio</a>
    </li>

    <li>
      <a href="#">Backhaul Radio</a>
    </li>

    <li>
      <a href="#">Basestation Switch or Router</a>
    </li>

    <li>
      <a href="#">Powerrail</a>
    </li>

    <li>
      <a href="#">UPS</a>
    </li>

    <li>
      <a href="#">ATS</a>
    </li>
  </ul>

  <ul class="nav nav-pills">
    <li class="active">
      <a href="#">Point to Point</a>
    </li>

    <li>
      <a href="#">Point to Multipoint</a>
    </li>
  </ul>

<%= form_for(@nms_update, :html => { :class => "form-inline"}) do |f| %>

  <%= f.text_field :service_type, placeholder: "service type", :class => "input-small" %>
  <br />
  <br />
  <%= f.text_field :basestation, placeholder: "Base Station", :class => "input-small" %>
  <%= f.text_field :direction, placeholder: "Direction", :class => "input-small" %>
  <%= f.text_field :device_make, placeholder: "Device Make", :class => "input-small" %>
  <%= f.text_field :device_model, placeholder: "Device Model", :class => "input-small" %>
  <%= f.text_field :ba_service_number, placeholder: "BA Number", :class => "input-small" %>
  <%= f.text_field :partner, placeholder: "Partner", :class => "input-medium" %>
  <%= f.text_field :business_name, placeholder: "Business Name", :class => "input-medium" %>
  <%= f.text_field :address, placeholder: "Address", :class => "input-large" %>
  <%= f.text_field :ip_address, placeholder: "IP Address", :class => "input-small" %>
  <%= button_tag(type: 'submit', class: "btn btn-info btn-small") do %>
    <i class="icon-key bigger-110"></i>
    Submit
   <% end %>

  <br />
  <br />
  <%= f.text_area :comments, placeholder: "Comments", :class => "autosize-transition span3",
            :style => "overflow: hidden; word-wrap: break-word; resize: horizontal; height: 100px;" %>

<% end %>
</div>

<%# Page Contend - End %>

<%= content_for :page_specific_javascripts do %>
<% end %>

<% content_for :inline_javascripts do %>
<% end %>


app/views/nms_updates/remove.html.erb
<% provide(:title, 'Remove') %>
<% provide(:page_header_description, 'Remove existing device from NMS') %>

<%= content_for :page_specific_stylesheets do %>
<% end %>

<%= content_for :inline_stylesheets do %>
  <%# ----------------------None---------------------- %>
<% end %>


<%# Page Contend - Start %>
<%# Page Contend - End %>

<%= content_for :page_specific_javascripts do %>
<% end %>

<% content_for :inline_javascripts do %>
<% end %>

app/views/nms_updates/update.html.erb
<% provide(:title, 'Update') %>
<% provide(:page_header_description, 'Update existing device in NMS') %>

<%= content_for :page_specific_stylesheets do %>
<% end %>

<%= content_for :inline_stylesheets do %>
  <%# ----------------------None---------------------- %>
<% end %>


<%# Page Contend - Start %>
<%# Page Contend - End %>

<%= content_for :page_specific_javascripts do %>
<% end %>

<% content_for :inline_javascripts do %>
<% end %>

app/views/process/process_page.html.erb
<% provide(:title, 'Process') %>
<% provide(:page_header_description, 'Process NMS changes') %>

<%= content_for :page_specific_stylesheets do %>
<% end %>

<%= content_for :inline_stylesheets do %>
  <%# ----------------------None---------------------- %>
<% end %>


<%# Page Contend - Start %>
<%# Page Contend - End %>

<%= content_for :page_specific_javascripts do %>
<% end %>

<% content_for :inline_javascripts do %>
<% end %>